### ISSUE TITLE
command blockage

### ISSUE THREAD

**Issue by CheatSupport** [MinelinkNetwork/CombatTagPlus#104] opened 2017-03-11 00:03 UTC
Hi.

I listed /wild on the blacklist of commands when in combat. But, I made it so all commands except commands on the whitelist are disabled. The command /wild is not on the whitelist, so how come players can still do this?

/Wild is from fbasics. Thanks!

latest version as of today!

**Comment by CheatSupport** [comment] 2017-03-11 00:03
@Byteflux @Techcable @rourke750 @ProgrammerDan @CraigEge

**Comment by Techcable** [comment] 2017-03-11 04:38
:expressionless: Can you gist the contents of your config.yml?

**Comment by CheatSupport** [comment] 2017-03-11 18:28
Sure, somehow this "fbasic" plugin has more priority over combattagplus. I believe Sudzzy has worked to make part of combattagplus, he also made fbasics. https://gist.github.com/CheatSupport/c96b86d602db40c01317e31af4028f04

**Comment by CheatSupport** [comment] 2017-03-14 17:53
@Techcable

**Comment by Techcable** [comment] 2017-03-18 04:37
I can't seem to reproduce this issue with the config you've given me.
Are you sure you're on the latest development build?

**Comment by CheatSupport** [comment] 2017-03-18 18:49
Yes, it won't block /wild from fbasics - somehow /wild has more priority

**Comment by CheatSupport** [comment] 2017-03-20 18:07
@Techcable are you able to make priority higher or just make it block 100% /wild and /wilderness for me on a seperate build?

**Comment by Byteflux** [comment] 2017-03-20 18:16
We do not "fix" problems that we can't reproduce. As far as we're concerned, this is a problem unrelated to CombatTagPlus and most likely an issue with conflicting plugins. If we can't recreate the issue on our own and actually prove that CombatTagPlus is at fault, we're not going to make any special changes.

**Comment by Byteflux** [comment] 2017-03-20 18:19
I've tested and verified that FBasics commands are correctly blocked by CombatTagPlus on the latest dev build. This issue can't be reproduced with just those 2 plugins, which means you either have an old FBasics version or your issue is related to another plugin interfering, either way it's not a CombatTagPlus problem. Closing.

**Closed as completed by Byteflux** 2017-03-20 18:19 UTC
